services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - VITE_APP_NAME=${APP_NAME}
        - VITE_APP_SHORT_NAME=${APP_SHORT_NAME}
        - VITE_APP_BACKGROUND_COLOR=${APP_BACKGROUND_COLOR}
        - VITE_APP_THEME_COLOR=${APP_THEME_COLOR}
        - VITE_API_BASE_URL="http://server:3000"

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
