-- AlterTable
ALTER TABLE "Academy" ADD COLUMN     "meta" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "tnBeginDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "tnEndDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
